### ISSUE TITLE
V2.08 -FixLocalSave Argument caused the experience gain to be minimal or zero

### ISSUE THREAD

**Issue by epi-k** [ferib/D2R-Offline#114]
Is this as expected? Seems like the game is now unplayable for me since -FixLocalSave completed all the quests and then the experience gain is minimal and so you can never progress in levels.

**Comment by SHDWatch** [comment]
how do i even add -FixLocalSave? i get sent to main menu after act 2?

**Comment by epi-k** [comment]
Any comments on this?

**Comment by csuhta** [comment]
You can create a new character and play the game using TCP/IP mode to advance quests normally. -FixLocalSave is a hack so that people can do single player and explore the game ASAP. -FixLocalSave also created a backup for you incase you need to restore it. 

> Any comments on this?

Bumping issues isn't necessary, and you are also not expressly entitled to the developer's time

**Comment by epi-k** [comment]
cool call the github police and report it then. Thanks
