### ISSUE TITLE
Any Custom Patch to change the resolution?

### ISSUE THREAD

**Issue by pigmich** [ferib/D2R-Offline#117]
For now, we unable to change the resolution in game setting, is here any way to change by using custom patch? Thanks

**Comment by mfrklic** [comment]
You can change the resolution to something smaller if in windowed mode for the new 3D engine, but appears fullscreen forces you to your windows resolution.

Sorry - I am not aware of a way to override this. Are you trying to run in a higher or lower resolution but still retain fullscreen? I believe the reason is the game does not run in true fullscreen -- it just runs in borderless fullscreen window mode when you select fullscreen so will always match your desktop resolution.
