### ISSUE TITLE
Some ejt & Crazyloon patches are not working

### ISSUE THREAD

**Issue by Hondelyk** [ferib/D2R-Offline#31]
Hi, 
So I'm using below patches.txt file:

> 0xD4AD68:9090
0xD4E25F:909090909090
0xCAFB9D:90B001
0x597E1C:90909090909090
0xC5E81C:9090C346455242: ~ MP stack corruption bypass
0xD615F2:909090909090909090909090909090909090909090909090909090: ~ show all calsses on load (shalzuth)
0x39FC03:9090909090909090909090909090909090909090: ~ allow chars to load (shalzuth)
0x1EE320E:90: ~ enableMultipleHirelings
0x1EE3202:90: ~ allowStatUnassignment
0x1EE3201:90: ~ displayItemLevel

But displaying item level and unassigning of stats is not working for me (but I can hire multiple hirelings). Am I doing something wrong?

**Comment by Hondelyk** [comment]
Closing. After few restarts it started working

**Comment by Hondelyk** [comment]
I have to reopen this, as it seems like in the end those patches are not working for me most of the time. I was able to successfully run those patches (allowStatUnassignment and displayItemLevel) twice. I am simply running D2ROffline.exe and according to logs everything is patched, but those features are not available for me. After many restarts it may work fine, but then next 10-20 restarts (with no changes to patches.txt or anything else whatsoever) it simply does not work. Is there something specific I am missing? Does patching is dependent on some timing/memory allocation?

**Comment by Crazyloon** [comment]
Maybe try setting them to :01: instead of :90: 

I have played for many hours with all of the following, with no issues:

```
0x1EE3200:90: ~ allowLadderRunewords
0x1EE3201:90: ~ displayItemLevel			
0x1EE31FF:90: ~ allowCowPortalWhenCowKingWasKilled
0x1EE3203:90: ~ enableUberQuest
0x1EE3202:90: ~ allowStatUnassignment
0x1EE3204:90: ~ allowSkillUnassignment (doesn't seem to be working)		
0x1EE320D:90: ~ enableWorldEventOffline (Assume Uber Diablo - haven't tested)
0x1EE320E:90: ~ enableMultipleHirelings
```

**Comment by ferib** [comment]
> I have played for many hours with all of the following, with no issues:
which patcher version did you use?

**Comment by Crazyloon** [comment]
I have been using the old version built with dotnet core. I also run it via powershell (`dotnet run --project .\D2ROffline.csproj D:\Games\D2R\Game.exe`), but I don't think that matters

**Comment by ferib** [comment]
@Hondelyk @Crazyloon Spoiler allert, ALL of those 'small' patches are located in the ``.data`` section...
This section is set to PAGE_READWRITE, meaning that you CAN already write to those locations. so why even bother using my patcher? Go ahead and grab Cheat Engine to edit memory in runtime ;D!

The reason why it did work on v2.0.2 or below is due to the timing issues, the v2.0.4 is much faster, meaning that it will patch code BEFORE the game is properly loaded to make sure that the patched code is executed (instead of the original one). 
The game may have overwritten the initial patches in the .data sections because guess what, the .data section is meant to read/write ;D.

To use this in Cheat Engine, attach to `Game.exe`, then "Add Address Manually" and type in `game.exe+OFFSET` to get it going!

**Comment by Crazyloon** [comment]
> ALL of those 'small' patches are located in the `.data` section...
> This section is set to PAGE_READWRITE, meaning that you CAN already write to those locations. so why even bother using my patcher? Go ahead and grab Cheat Engine to edit memory in runtime ;D!

The reason to use the patcher is because it has the potential to let users enter patches via text file and not have to mess with cheat engine.

Is there potential to just slow the application down slightly with a thread sleep? I assume it could just sleep for a second or less and work fine.
