### ISSUE TITLE
V2.0.4 Crashes

### ISSUE THREAD

**Issue by SpudMillions** [ferib/D2R-Offline#54]
While using the altest version 2.0.4 the game keeps crashing after a period of time.
I used the 2.0.0 version and it works perfect.

**Comment by ferib** [comment]
Can you tell us which `patches.txt` you used? Where they both the same `patches.txt` file on v2.0.4 and v2.0.0?

**Comment by SpudMillions** [comment]
In both I downloaded the source zip and built the executables. 

In v2.0.4 it had the patches.txt in the bin so I used that one. 

In v2.0.0 it was a separate file in the release.

I compared the two and they looked the same though.

**Comment by ShamblerDK** [comment]
Got the exact same issue with 2.0.5. The 2.0.0 version won't even run. (Yes, I allowed the file in Windows Defender.)

I also tried to use patches.txt from version 2.0.0 for version 2.0.5 of the exe.

Did you add some logging to this software?

(I'm used to do tons of error reporting for Minecraft mods. Been running a Minecraft community + server for many years now.)

**Comment by ferib** [comment]
These crashes are caused due to timing issues, your device is either too slow and patches before the anti-cheat is done scanning or too later when the code that gets patched is already executed and the patch itself is no longer effective.

You can tweak this delay at `program.cs` somewhere in line `79`, simply increase the argument of `Thread.Sleep` and that should stop crashing, just don't set it too high or patches won't be effective anymore.

**Comment by ShamblerDK** [comment]
> These crashes are caused due to timing issues, your device is either too slow and patches before the anti-cheat is done scanning or too later when the code that gets patched is already executed and the patch itself is no longer effective.
> 
> You can tweak this delay at `program.cs` somewhere in line `79`, simply increase the argument of `Thread.Sleep` and that should stop crashing, just don't set it too high or patches won't be effective anymore.

Would it be possible to make it a command line option for those people, who hasn't set up a dev environment?

**Comment by ferib** [comment]
> > These crashes are caused due to timing issues, your device is either too slow and patches before the anti-cheat is done scanning or too later when the code that gets patched is already executed and the patch itself is no longer effective.
> > You can tweak this delay at `program.cs` somewhere in line `79`, simply increase the argument of `Thread.Sleep` and that should stop crashing, just don't set it too high or patches won't be effective anymore.
> 
> Would it be possible to make it a command line option for those people, who hasn't set up a dev environment?

Sure, that's not a bad idea, feel free to re-write the arg handling and add some extra command lines stuff in it, PR's are welcome in the `beta` branch.

**Comment by ericschn** [comment]
Submitted a PR for specifying delay amount via command line argument in beta branch

**Comment by JamieeLee** [comment]
I tested Thread.Sleep(500); // NOTE: patch before this to get language working, may cause a crash?
the patch still seems to load fine without any ill effects, granted game boot-up took a tad longer, that also could because I had visual studio running in the background as well.   Mind you 500 ms is still only.5th a second I wold not recommend going beyond that but the game seems more stable.

**Comment by ferib** [comment]
https://github.com/ferib/D2R-Offline#-fixlocalsave
