### ISSUE TITLE
Save and Exit (using 2.0.4) freezes entire PC

### ISSUE THREAD

**Issue by CalMac91** [ferib/D2R-Offline#69]
I know this sounds kinda wild, but as of like a few hours ago, my save and exits from my own hosted TCP/IP with an active character  causes my whole PC to be unresponsive. Game essentially freezes (along with everything else) at the black screen with Diablo II Resurrected Technical Alpha in bottom right hand corner. Can't alt tab, cant ctr alt dlt, have to restart whole PC. This happening to anyone else? Thanks.

**Comment by mfrklic** [comment]
2.0.4 has been really stable for me! I had stability issues with 2.0.5 for some reason. I only crashed once with 2.04 in TCP/IP when I accidently clicked on my brother's character to initiate a trade but pretty sure that was the Alpha blowing up on it's own.

**Comment by diaderik** [comment]
I have been playing on version 2.0.5 for more than 5 hours. Сompiled exe-file it myself from source code.

**Comment by ferib** [comment]
I noticed that Windows is heavily scanning my patcher when I use it. Sometimes when I start debugging in my Visual Studio I hear my PC fans spin up like crazy, so I check out the CPU usage to see 'Windows anti-malware executable" or something similar take up a lot of CPU usage. I can imagine that maybe Windows defender performs one of those scans on your device, making your device unresponsive.

You mentioned this happens when you 'save and exit'? Makes sense to me that Windows would wait, the game takes up a lot of CPU resources so it may wait until you 'save and exit' and starts doing some heavy scanning.

I suggest whitelisting the file in anti-virus or build it yourself. But I'm afraid Windows will continue to suck up your resources until you uninstall it.

**Comment by CalMac91** [comment]
Hi Ferib, my apologies for the delay in response. Your reply is much appreciated. Yes, it was happening when saving and exiting. It must be a windows-side thing, because lately it hasn't been happening at all. I do have the app whitelisted, but that was done after it had stopped giving me trouble. My only remaining issues on 2.0.4 are that sometimes on first start, my last played character doesn't load at main screen and some maps overlays are screwy in game, but I know these are existing topics. I'll check out latest release and test. Thanks again for all your work!

**Comment by ferib** [comment]
Good to hear you got it figured out, @CalMac91.
Yeah, those map overlays are part of the alpha game issues hehe, hope the new game release will fix those ;).
