### ISSUE TITLE
2.0.6 Crashing

### ISSUE THREAD

**Issue by bvandy123** [ferib/D2R-Offline#91]
updated to latest patch because of crash issues. Now game crashes within 2 minutes of opening. Tried adding delay, it would not open at all after that. it errored.

**Comment by fuba82** [comment]
Hmm, maybe because the `-Delay` argument does nothing as i see in the Code because:  
The `Patcher.cs` line 46 still is `Thread.Sleep(25);` and this is the "crash point" if i understand it right?!  

And also in the Method `Patcher.Start` the value `int crashDelay = 25` will never used again in `Patcher.cs` so it does not care the Argument it passes in `Program.cs` at line 68

You need to change `Patcher.cs` line 46 from ``Thread.Sleep(25);`` to `Thread.Sleep(crashDelay);` to make `-Delay` Command work, else it's just an empty variable ^^

**Comment by ferib** [comment]
> @bvandy123 you're right, because the `-Delay` command is currently not working!
> 
> @ferib
> It is because the `-Delay` argument does nothing as i see in the Code:
> The `Patcher.cs` line 46 still is `Thread.Sleep(25);` and this is the "crash point" if i understand it right?!
> 
> And in the Method `Patcher.Start` the value `int crashDelay = 25` will never used again in `Patcher.cs` so it does not care the Argument it passes in `Program.cs` at line 68
> 
> You need to change `Patcher.cs` line 46 from `Thread.Sleep(25);` to `Thread.Sleep(crashDelay);` to make `-Delay` Command work, else it's just an empty variable ^^

this is fixed in `beta`
